swyxio/spark-joy

README.md
- Add CSS Doodle
- Add a few links around creative coding
=> Add CSS doodle and a few links around creative coding

README.md
Best repo name 🤣 
Added a couple of packages I think are cool!
=> Add burger and confetti links

README.md
Sorry about the unwarranted PR.
I thought this https://www.colorbox.io/ link by `Lyft Design` team was another great color picker generator.
=> Added 'ColorBox' by Lyft Design in 'Color Picking' section

README.md
I thought Autodraw.com by Google would be a fantastic addition to the Icon category.
=> added autodraw.com to icons category

README.md
We had a great episode with Erik Kennedy that is worth including. I also improved the formatting of the podcast links for uniformity and readability ✊
=> Add Changelog podcast link

README.md
Hi! Nice repo, congratulations!
are PRs welcome? if yes, I'd like to add [react-genie](https://github.com/kitze/react-genie) inside the "simple animation" list under "React" topic. It is a great and simple way to add smooth animations insite a react app.
=> add react-genie under react simple animation

README.md
Many of these links are to my own domain. Please only add if they meet your quality bar :)
=> Added links; fixed Changelog podcast broken link

README.md
This is my own resource, so feel free to reject if it's too hard on the self-promo. That said, this is the most-downloaded episode of our podcast for all time and might be a good primer on some laws/principles of design that would be helpful for devs (https://designdetails.fm/episodes/220880)
=> Add Principles of Design episode of Design Details

README.md
Hi,
I've been seeing [Water.css](https://watercss.kognise.dev/) start to pop up in a few places and have actually found it really smooth and easy to use (I converted one of my projects to it and it's been a breeze - timrossback/kira@59b716a826bf29a56acf3bde01f915917474ab91). It's super simple to set up since it uses native HTML elements for styling rather than classes and is responsive with both a light and dark theme off the shelf. I think it would be a nice addition to the others already here.
Thanks!
=> Adding Water.css to CSS Frameworks

README.md
Hey @sw-yx 
First of all thanks for share https://public-apis.io here.
This project is different. So, pushing to a new line.
=> public-apis.io is diffrent project

README.md
https://notchris.net/patterns/
=> Adds https://notchris.net/patterns/

README.md
it's not just nasa pictures :)
=> remove 'nasa' search string

README.md
Geri Reid's summary is a11y focused and is the best guide I've seen.
=> Update README with additional forms reference

README.md
=> Fix a small typo in readme

README.md
Added this pattern generator https://doodad.dev/pattern-generator/ I saw on HN here: https://news.ycombinator.com/item?id=26093710
=> Added doodad.dev/pattern-generator

README.md
This PR adds more sound sites. It also fixes the broken YouTube Audio Library one.
=> feat: add more sounds

README.md
Love the repo. Saves me a lot of time.
Added a sound link I use from time to time. I find it more user-friendly than some other ones.
Thanks
=> added Sound resource

README.md
- Add Atmos to Colors section under Palette Generators
- Sorted by Alpabet
Thanks! 🙂
=> Add Atmos tool

README.md
Added https://designstripe.com, it has thousands of free curated illustrations + a web editor that makes it easy to customize colors, objects, characters, etc.
=> Add designstripe

README.md
Hello,
I'd like to suggest [Polygonjs](https://polygonjs.com), a WebGL design tool, if that's okay.
Don't hesitate if you have any questions,
=> add https://polygonjs.com in webgl

README.md
Snapmuse.com added for music section
=> Snapmuse.com added

README.md
Added under "Helpful podcasts/talks/articles"
=> Add how to design great keyboard shortcuts blogpost

README.md
Bulk edit and generate videos automatically with custom templates
=> Add Shotstack video editing API

README.md
added: pika.style, instantly turns boring screenshots into beautiful images and device mockups
under: Graphics and SVG Illustrations > Device Mocks
I think users would find Pika useful :)
=> add: pika.style

README.md
Hi @sw-yx ,
I'm the maintainer of Circum Icons a library of 285 icons. You can see them at [circumicons.com](https://circumicons.com/) and you can find our repo [here](https://github.com/Klarr-Agency/Circum-Icons). Our icons are available for React, Vue and Svelte.
Thank you!
=> Circum Icons icon library

README.md
Added a new website Landings under the design inspo category
Landings is a curated directory of hundreds of landing page templates that can be filtered across different categories
=> Added new website for design inspo

README.md
One of the best things ever. It's compatible with Tailwind and it uses Radix.
=> adding https://ui.shadcn.com/

README.md
Concrete.css is a minimal classless CSS utility that I think fits perfectly in this list!
=> Add concrete.style

README.md
=> Add ChatUML.com to the Code-based Diagram Tools

README.md
=> Added Spinner/Sound sources

README.md
I've added Mossaik, a free SVG Pattern generator with different tools.
=> Added Mossaik

README.md
- The link to the gradient generator appeared twice; combined them
- Noted new v2 feature - that you can use 8 color spaces
=> de-duping link + updating for v2 features

README.md
- Adding creatica.app, a design tool which generates website SVG backgrounds and patterns.
=> Add Creatica.app - Generate SVG backgrounds & Patterns

README.md
I've developed a favicon generator site (https://favicon.inbrowser.app/) with following features:
* Tweak the settings and see preview in real time.
* Pure frontend. Everything is processed in browser. No privacy risk. Fast.
* Works without a network connection using PWA.
* Support all image formats supported by browser.
* `"purpose": "any"` and `"purpose": "maskable"` support.
* Outputs are losslessly minified using `oxipng` and `svgo`.
I hope you can add my tool to assist more people in generating favicon assets with ease.
=> add Favicon InBrowser.App

README.md
Hello!
Thanks for the valuable resources! 💖
I noticed the a11yresources link on the list was expired.
The project has moved to the Stark Library, so I updated the link to this one.
=> Updating a11yresources link
